language: node_js
node_js:
    - "0.10"
install:
    - "npm install"
    - "npm install yeti"
    - "gulp init"
    - "gulp build"
script:
    - "gulp lint"
    - "yeti --hub http://yeti-1.liferay.com"
