language: node_js
os:
    - linux
    - osx
node_js:
    - "0.10"
    - "0.11"
before_install:
    - "npm install -g gulp"
install:
    - "npm install"
    - "gulp init"
    - "gulp build"
script:
    - "gulp lint"
    - "gulp test"
after_script:
    - "gulp ci-docs"
env:
    - TEST_SUITE=units
    - TEST_SUITE=integration
addons:
    sauce_connect:
        username: "foo"
        access_key: "bar"
matrix:
    - allow_failures:
        - env: TEST_SUITE=integration
    - exclude:
        - os: osx
          env: TEST_SUITE=integration
        - env:
          - TEST_SUITE=integration
          - TRAVIS_PULL_REQUEST
    fast_finish: true
notifications:
    irc: "chat.freenode.net#henvic"
    email: false
    slack: '<account>:<token>#alloyui'
