language: node_js
os:
    - linux
    - osx
node_js:
    - "0.10"
    - "0.11"
before_install:
    - "npm install -g gulp"
install:
    - "npm install"
    - "gulp init"
    - "gulp build"
script:
    - "gulp lint"
    - "gulp test"
