language: node_js
os:
    - linux
    - osx
node_js:
    - "0.10"
    - "0.11"
before_install:
    - "npm install -g gulp"
install:
    - "npm install"
    - "gulp init"
    - "gulp build"
script:
    - "gulp lint"
    - "gulp test"
after_script:
    - "istanbul instrument src -x "[ **/node_modules/**, **/test/**, **/tests/**, **/meta/** ]" -o coverage"
    - "cat lcov.info | codeclimate"
env:
    - TEST_SUITE=units
    - TEST_SUITE=integration
addons:
    code_climate:
        repo_token:
            secure: "diTOa3nv31vkodOtFw7/1BpQIOzYBv9zKPuPa7sOXCp0YHWurZziyWnrwuTgvypwR9ugwMMaDSoEN8+7TtEQU7xVugZi0UN4JJ21bFrryz8Zes29Ktuh1SvKc+g/1b0hJpqQeVakXMrNVvyURDMAmw9C4qTZacQsOTW77wpttxo="
matrix:
    - allow_failures:
        - env: TEST_SUITE=integration
    - exclude:
        - os: osx
          env: TEST_SUITE=integration
        - env:
          - TEST_SUITE=integration
          - TRAVIS_PULL_REQUEST
    fast_finish: true
notifications:
    irc: "chat.freenode.net#henvic"
    email: false
    slack:
        secure: "BCmPmv4v32HZCeRys31lAbmpXpylcNrWmScyNGcP7O4FQbVQimhsxnQU6SZIlwSD/HP0Bfc5wIgLteQjMJxYfEk1mnm4gDI2SRSeLE/18TSRGgNMPXgYh6t3uRKHTu8Z8jNs6zPhjW9Yi5TsGs3ebFY+7u32Ke8odAwcpz89EFk="
