language: node_js
node_js:
    - "0.10"
    - "0.11"
install:
    - "npm install -g codeclimate-test-reporter"
    - "npm install -g istanbul"
    - "npm install"
    - "gulp init"
    - "gulp build"
script:
    - "gulp lint"
    - "gulp coverage"
    - "istanbul report --root coverage text"
after_script:
    - "codeclimate < coverage/lcov.info"
addons:
    code_climate:
        repo_token:
            secure: "diTOa3nv31vkodOtFw7/1BpQIOzYBv9zKPuPa7sOXCp0YHWurZziyWnrwuTgvypwR9ugwMMaDSoEN8+7TtEQU7xVugZi0UN4JJ21bFrryz8Zes29Ktuh1SvKc+g/1b0hJpqQeVakXMrNVvyURDMAmw9C4qTZacQsOTW77wpttxo="
notifications:
    irc: "chat.freenode.net#henvic"
    email: false
    slack:
        secure: "BCmPmv4v32HZCeRys31lAbmpXpylcNrWmScyNGcP7O4FQbVQimhsxnQU6SZIlwSD/HP0Bfc5wIgLteQjMJxYfEk1mnm4gDI2SRSeLE/18TSRGgNMPXgYh6t3uRKHTu8Z8jNs6zPhjW9Yi5TsGs3ebFY+7u32Ke8odAwcpz89EFk="
